export const DUMMY_DATA = [
  { id: 1, name: "yussuf ajao", img: "/my image.jpeg", company: "softerlane" },
  {
    id: 2,
    name: "yussuf ajao",
    img: "/my image.jpeg",
    company: "softerlane",
  },
  { id: 3, name: "yussuf ajao", img: "/my image.jpeg", company: "softerlane" },
  { id: 4, name: "yussuf ajao", img: "/my image.jpeg", company: "softerlane" },
  { id: 5, name: "yussuf ajao", img: "/my image.jpeg", company: "softerlane" },
  { id: 6, name: "yussuf ajao", img: "/my image.jpeg", company: "softerlane" },
  { id: 7, name: "yussuf ajao", img: "/my image.jpeg", company: "softerlane" },
  { id: 8, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 9, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 10, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 11, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 12, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 13, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 14, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 15, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 16, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 17, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 18, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 19, name: "yussuf ajao", img: "/my image.jpeg" },
  { id: 20, name: "yussuf ajao", img: "/my image.jpeg" },
];